{left_ankle_pitch: 0.0, left_ankle_roll: 0.0, left_ankle_yaw: 0.0, left_elbow_pitch: 30.0,
  left_elbow_yaw: 80.0, left_hip_pitch: -5.0, left_hip_roll: 5.0, left_hip_yaw: 0.0,
  left_knee_pitch: 10.0, left_shoulder_roll: -60.0, left_shoulder_yaw: 15.0, left_wrist_pitch: 0.0,
  left_wrist_roll: 0.0, left_wrist_yaw: 0.0, name: human, neck_pitch: 0.0, neck_roll: 0.0,
  neck_yaw: 0.0, pelvis_pitch: 0.0, pelvis_roll: 0.0, pelvis_yaw: 180.0, right_ankle_pitch: 0.0,
  right_ankle_roll: 0.0, right_ankle_yaw: 0.0, right_elbow_pitch: 30.0, right_elbow_yaw: -80.0,
  right_hip_pitch: -5.0, right_hip_roll: -5.0, right_hip_yaw: 0.0, right_knee_pitch: 10.0,
  right_shoulder_roll: 60.0, right_shoulder_yaw: -15.0, right_wrist_pitch: 0.0, right_wrist_roll: 0.0,
  right_wrist_yaw: 0.0, sensor_frame_name: /virtual_humanoid_sensor, torso_pitch: 0.0,
  torso_roll: 0.0, torso_yaw: 0.0, use_displacement: false}
